### ISSUE TITLE
Could not select latest Version in Libraray Manager

### ISSUE THREAD

**Issue by pischky** [mrrwa/LocoNet#33]
LocoNet/library.properties says that 1.1.9 is the current (latest) version.
But in the Arduino-IDE (Version 1.8.19) the latest Version I can select is 1.1.4.

Are there any release files missing? 

Yes, I know that I can download a zip and copy manually, but I assumes that it should be much easier....

![Clipboard01](https://user-images.githubusercontent.com/15169990/170881137-cd27e16f-569b-4035-a0fb-c6ce907d3eaf.jpg)

**Comment by kiwi64ajs** [comment]
Its pretty much just because I've merged in some pretty large and potentially disruptive PRs from others that add support for other CPUs, which I don't have setup to test at all, so I was being conservative.
However, given your prompting, I guess its probably about time they were released and if there are issues - we'll just have to sort them.
I've created the 1.19 tag and pushed that to the Git Repo, so that should propagate through tot he Arduino Library manager in the new few hours

**Comment by pischky** [comment]
Thanks!
If I find something not working in 1.1.9 I will write a new Issue.

**Comment by kiwi64ajs** [comment]
Cool. I just checked and the Arduino Library Manager looks to offer the 1.1.9 version for install now.

Enjoy
